version: "3.8"

services:
  iceberg-manager:
    image: faroukdaboussi0/iceberg-manager:latest
    container_name: iceberg_manager
    environment:
      - CATALOG_URI=http://iceberg:8181/
      - WAREHOUSE=s3://asel/
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - S3_REGION=us-east-1
    networks:
      - lakehouse_net
    ports:
      - "8000:8000" 

networks:
  lakehouse_net:
    external: true
